name: test_to_do
description: A new Flutter project.

publish_to: 'none'     

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  logger: ^1.1.0
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  build_runner: ^2.1.11
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  json_annotation: ^4.5.0
  uuid: ^3.0.6
  connectivity_plus: ^2.3.5
  shared_preferences: ^2.0.15
  file_picker: ^3.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter    
  flutter_lints: ^1.0.0
  json_serializable: ^6.2.0
  hive_generator: ^1.1.3

flutter:    
  uses-material-design: true

  fonts:
    - family: SfUiDisplay
      fonts: 
        #- asset: fonts/sf_ui_display.otf
        - asset: fonts\sf_ui_display_semibold.otf
          weight: 500

    
    
    
    

    
    

    
    

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
